import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// @ts-expect-error globals.css is handled by Next.js at build time.
import "./globals.css";
import Providers from "./providers";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          {children}
          <Toaster
            position="top-center"
            toastOptions={{
              style: {
                fontFamily: "var(--font-geist-sans)",
                background: "#",
                color: "#",
                fontSize: "14px",
                padding: "12px 16px",
                borderRadius: "8px",
                boxShadow: "0 2px 6px rgba(0, 0, 0, 0.1)",
              },
              success: {
                style: {
                  background: "#16a34a",
                  color: "#fff",
                },
                iconTheme: {
                  primary: "#",
                  secondary: "#",
                },
              },
              error: {
                style: {
                  background: "#dc2626",
                  color: "#fff",
                },
                iconTheme: {
                  primary: "#",
                  secondary: "#",
                },
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}